export const techs = [
    "nodejs", "nextjs", "react", "vuejs", "angular", "svelte", "ember",
    "typescript", "javascript", "python", "java", "csharp", "cpp", "c",
    "php", "ruby", "go", "swift", "kotlin", "rust", "scala", "perl", "lua",
    "django", "flask", "laravel", "spring", "express", "fastapi", "hapi",
    "mongodb", "mysql", "postgresql", "sqlite", "redis", "cassandra", "oracle",
    "docker", "kubernetes", "aws", "azure", "gcp", "firebase", "heroku",
    "graphql", "apollo", "relay", "tailwindcss", "bootstrap", "foundation",
    "materialui", "chakraui", "antdesign", "bulma", "semanticui", "sass", "less",
    "webpack", "rollup","ejs", "parcel", "vite", "babel", "eslint", "prettier",
    "jest", "mocha", "chai", "cypress", "selenium", "puppeteer", "playwright",
    "git", "github", "gitlab", "bitbucket", "linux", "windows", "macos",
    "npm", "yarn", "pnpm", "vscode", "vim", "emacs", "atom",
    "cordova", "reactnative", "flutter", "electron", "nest", "nestjs",
    "socketio", "mqtt", "rabbitmq", "kafka", "apachekafka",
    "stripe", "paypal", "braintree", "square", "jenkins", "circleci",
    "travisci", "githubactions", "ansible", "terraform", "prometheus",
    "grafana", "newrelic", "datadog", "elasticsearch", "logstash", "kibana",
    "apache", "nginx", "iis", "supabase", "hasura", "prisma",
    "threejs", "d3", "chartjs", "opencv", "tensorflow", "pytorch",
    "openai", "huggingface", "fastify", "nestjs", "graphql-yoga",
    "vitest", "playwright", "storybook", "selenium", "puppeteer",
    "tailwindcss", "postcss", "eslint", "prettier", "stylelint",
    "nx", "lerna", "babel", "rollup", "vite",
    "karma", "mocha", "jasmine", "ava", "tap", "couchdb", "dynamodb", "firebase", "redis",
    "apache-cassandra", "apache-hadoop", "apache-spark",
    "solidity", "web3js", "ethers", "truffle", "hardhat",
    "docker-compose", "minikube", "helm", "istio",
    "flutter", "dart", "reactnative", "swiftui",
    "android", "ios", "xamarin", "unity", "unreal-engine",
    "graphql", "restapi", "soap", "grpc",
    "oauth2", "openid", "jwt", "saml",
    "prometheus", "grafana", "newrelic", "elastic-apm",
    "firebase", "amplify", "appsync", "lambda",
    "circleci", "jenkins", "teamcity", "bamboo",
    "puppeteer", "playwright", "webdriverio",
    "openstack", "vmware", "hyperv",
    "google-analytics", "matomo",
    "redux", "mobx", "zustand", "recoil",
    "apollo-client", "urql", "relay",
    "rxjs", "xstate", "immer",
    "material-ui", "chakra-ui", "ant-design", "bootstrap",
    "tailwindcss", "foundation", "bulma",
    "storybook", "mdx",
    "babel", "eslint", "prettier",
    "vite", "webpack", "rollup",
];
  


export const projects = [
    {
      title: "DevHub Discussions",
      description: "An open-source forum for developers to discuss bugs, features, and trends in real-time.",
      username: "mohammed_dev",
      avatar: "https://i.pravatar.cc/150?img=12",
    },
    {
      title: "Code Snippet Vault",
      description: "Store, search, and share reusable code snippets across languages with GitHub sync.",
      username: "sara.codes",
      avatar: "https://i.pravatar.cc/150?img=32",
    },
    {
      title: "OpenTasks Board",
      description: "A simple kanban-style open-source task manager built with React and Firebase.",
      username: "amina_uiux",
      avatar: "https://i.pravatar.cc/150?img=21",
    },
    {
      title: "AI Resume Builder",
      description: "Generate developer resumes using AI and Markdown templates.",
      username: "yas.dev",
      avatar: "https://i.pravatar.cc/150?img=45",
    },
    {
      title: "Realtime ChatKit",
      description: "A minimal WebSocket-based chat component with theming and end-to-end encryption.",
      username: "khalil_data",
      avatar: "https://i.pravatar.cc/150?img=3",
    },
    {
      title: "GreenDash",
      description: "An eco-friendly dashboard template focused on environmental analytics.",
      username: "niss_js",
      avatar: "https://i.pravatar.cc/150?img=29",
    },
    {
      title: "Translatify",
      description: "An open-source AI translator with support for 100+ languages and offline caching.",
      username: "salma_techie",
      avatar: "https://i.pravatar.cc/150?img=4",
    },
    {
      title: "OpenLearning LMS",
      description: "A lightweight, open-source learning platform for technical courses.",
      username: "sal_fullst",
      avatar: "https://i.pravatar.cc/150?img=24",
    },
    {
      title: "DevMeet Scheduler",
      description: "Schedule developer meetups with voting, calendar sync, and timezone detection.",
      username: "nourr_backend",
      avatar: "https://i.pravatar.cc/150?img=41",
    },
    {
      title: "MarkDown Editor Pro",
      description: "Collaborative markdown editor with live preview and export to PDF/HTML.",
      username: "karima_nodes",
      avatar: "https://i.pravatar.cc/150?img=36",
    },
  ]
  