export const techs = [
    "nodejs", "nextjs", "react", "vuejs", "angular", "svelte", "ember",
    "typescript", "javascript", "python", "java", "csharp", "cpp", "c",
    "php", "ruby", "go", "swift", "kotlin", "rust", "scala", "perl", "lua",
    "django", "flask", "laravel", "spring", "express", "fastapi", "hapi",
    "mongodb", "mysql", "postgresql", "sqlite", "redis", "cassandra", "oracle",
    "docker", "kubernetes", "aws", "azure", "gcp", "firebase", "heroku",
    "graphql", "apollo", "relay", "tailwindcss", "bootstrap", "foundation",
    "materialui", "chakraui", "antdesign", "bulma", "semanticui", "sass", "less",
    "webpack", "rollup", "parcel", "vite", "babel", "eslint", "prettier",
    "jest", "mocha", "chai", "cypress", "selenium", "puppeteer", "playwright",
    "git", "github", "gitlab", "bitbucket", "linux", "windows", "macos",
    "npm", "yarn", "pnpm", "vscode", "vim", "emacs", "atom",
    "cordova", "reactnative", "flutter", "electron", "nest", "nestjs",
    "socketio", "mqtt", "rabbitmq", "kafka", "apachekafka",
    "stripe", "paypal", "braintree", "square", "jenkins", "circleci",
    "travisci", "githubactions", "ansible", "terraform", "prometheus",
    "grafana", "newrelic", "datadog", "elasticsearch", "logstash", "kibana",
    "apache", "nginx", "iis", "supabase", "hasura", "prisma",
    "threejs", "d3", "chartjs", "opencv", "tensorflow", "pytorch",
    "openai", "huggingface", "fastify", "nestjs", "graphql-yoga",
    "vitest", "playwright", "storybook", "selenium", "puppeteer",
    "tailwindcss", "postcss", "eslint", "prettier", "stylelint",
    "nx", "lerna", "babel", "rollup", "vite",
    "karma", "mocha", "jasmine", "ava", "tap",
    "mongodb", "couchdb", "dynamodb", "firebase", "redis",
    "apache-cassandra", "apache-hadoop", "apache-spark",
    "solidity", "web3js", "ethers", "truffle", "hardhat",
    "docker-compose", "minikube", "helm", "istio",
    "flutter", "dart", "reactnative", "swiftui",
    "android", "ios", "xamarin", "unity", "unreal-engine",
    "graphql", "restapi", "soap", "grpc",
    "oauth2", "openid", "jwt", "saml",
    "prometheus", "grafana", "newrelic", "elastic-apm",
    "firebase", "amplify", "appsync", "lambda",
    "circleci", "jenkins", "teamcity", "bamboo",
    "puppeteer", "playwright", "webdriverio",
    "openstack", "vmware", "hyperv",
    "google-analytics", "matomo",
    "redux", "mobx", "zustand", "recoil",
    "apollo-client", "urql", "relay",
    "rxjs", "xstate", "immer",
    "material-ui", "chakra-ui", "ant-design", "bootstrap",
    "tailwindcss", "foundation", "bulma",
    "storybook", "mdx",
    "babel", "eslint", "prettier",
    "vite", "webpack", "rollup",
];
  